[languages.en.params]
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
# weight = 1
rtl = true

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "Rainbow Crow, LLC."
  image = "/favicon-32x32.png"
  headline = "Rainbow Crow, LLC."
#  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#  links = [
#    { twitter = "https://twitter.com/" },
#  ]
