[languages.en.params]
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = true

title = ""
logo = "img/logo.png"
description = ""
# copyright = "&copy; 2023 Rainbow Crow, LLC. &#9755; 176 Camden Cay Drive, St. Augustine FL 32086 &#9754;"

dateFormat = "2 January 2006"

[author]
  name = "Rainbow Crow, LLC."
  image = ""
  headline = ""
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#  links = [
#    { twitter = "https://twitter.com/" },
#  ]
