[languages.en.params]
languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
# weight = 1
rtl = true

[params]

title = ""
logo = "img/logo.png"
description = "RC Design"
dateFormat = "2 January 2006"

[author]
  name = "Rainbow Crow, LLC."
  image = ""
  headline = ""
  bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#  links = [
#    { twitter = "https://twitter.com/" },
#  ]
